### ISSUE TITLE
Letras que no aparecen X veces se marcan como válidas X veces

### ISSUE THREAD

**Issue by mcornella** [danielfrg/wordle.es#1]
Por ejemplo, en el wordle número 3, la A aparece solo una vez, pero si se pone una palabra con varias As todas se marcarán como que aparecen, en amarillo o verde según la posición en que estén.

![IMG_20220109_163842.jpg](https://user-images.githubusercontent.com/1441704/148689375-2795f8d3-07cc-4206-82b3-eecd61c1f92c.jpg)

El wordle original solo marca una de las As como correcta, la que está en posición correcta si hay alguna o cualquier otra si no hay. El resto las pinta grises.

**Comment by danielfrg** [comment]
Gracias! Debería estar arreglado en https://github.com/danielfrg/wordle.es/commit/637f6ba9aec70721e1dc81b9bd7de24fcf0f2573

**Comment by mcornella** [comment]
Sí funciona gracias! :)
