### ISSUE TITLE
Modo oscuro

### ISSUE THREAD

**Issue by hasecilu** [danielfrg/wordle.es#3]
1. Falta un tema oscuro nativo
2. Si usas alguna extensión que te muestre tu navegador en modo oscuro (yo uso Dark Reader) esta invierte los colores usados en `WORDLE(ES)`, también he usado `WORDLE` en inglés en `powerlanguage.co.uk` y en esta página los colores no se invierten, incluso sin activar el modo oscuro del juego pero con mi extensión activada. Estoy seguro que se puede cambiar la forma en la que muestras los colores para que no se inviertan al usar alguna extensión. Se muestra una imagen abajo.
3. Para que la interfaz esté totalmente en español sería conveniente cambiar la palabra `ENTER` del teclado por `INGRESAR` aunque sería algo muy largo o cambiar a un icono como el que tiene un teclado convencional (esa flecha que va de arriba a la izquierda). Aún así la palabra `ENTER` está bastante estandarizada.

![WORDLE](https://user-images.githubusercontent.com/53124818/149037987-2367b646-f42f-40d1-9297-0e6fec02e81c.png)

Que bueno que existe esta versión en español, me gustó el concepto. Saludos.

**Comment by danielfrg** [comment]
Gracias por los comentarios.

Le añadi una version oscura parecida a la version original. Aunque me imagino que con tu extension aun se va a ver raro. Lo intentare mirar pero por ahora cerrar el issue ya que por lo menos ya hay un modo oscudo.

Si, lo de `ENTER` nunca me termino de gustar pero creo que es bastante estandar en estos momentos e `INGRESAR` es un poco larga para los moviles.
